#!/bin/bash
set -e

oc new-project sonataflow-infra
oc create secret generic sonataflow-psql-postgresql --from-literal=postgres-username=postgres --from-literal=postgres-password=postgres
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install sonataflow-psql bitnami/postgresql --version 12.x.x -f ${REPO}/postgresql/values.yaml
oc wait pods -n sonataflow-infra sonataflow-psql-postgresql-0 --for=condition=Ready --timeout 5m
