#!/bin/bash
set -e

helm repo add orchestrator https://parodos-dev.github.io/orchestrator-helm-chart
oc new-project orchestrator
if [ -n "$VERSION" ]; then
    helm install orchestrator orchestrator/orchestrator --set rhdhOperator.github.token=$GITHUB_TOKEN --version=$VERSION
else
    helm install orchestrator orchestrator/orchestrator --set rhdhOperator.github.token=$GITHUB_TOKEN
fi
